---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theauto1/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R articles $DEPLOYPATH
    - /bin/cp -R members $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
